backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "event" # Used in routes, e.g., /admin/collections/blog
    label: "Event" # Used in the UI
    folder: "content/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string" }
      - {label: "Date", name: "when", widget: "string" }
      - {label: "Time", name: "time", widget: "string", required: false }
      - {label: "Location", name: "where", widget: "string" }
      - {label: "Description", name: "what", widget: "string", required: false }
      - {label: "Link", name: "cta", widget: "string", required: false }
      - {label: "Button Message", name: "ctaMessage", widget: "string", required: false, default: "link"}
      - {label: "Image", name: "thumbnail", widget: "image", required: false }
  - label: "Site Config"
    name: "config"
    files: 
      - label: "Site Banner"
        name: "banner"
        file: "data/site_conf/banner.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string", required: false}